### ISSUE TITLE
susieR not installing automatically

### ISSUE THREAD

**Issue by bschilder** [RajLabMSSM/echolocatoR#33]
susieR is listed as a Remote in the DESCRIPTION file...

```
Remotes:
  github::stephenslab/susieR 
```

but isn't automatically being installed with echolocatoR for some reason. Including susieR as part of `extra_installs()` for now.

**Comment by bschilder** [comment]
Tried adding [@*release syntax](https://github.com/r-lib/remotes/blob/HEAD/vignettes/dependencies.Rmd):

```
Remotes:
  github::stephenslab/susieR@*release 
```

**Comment by jdblischak** [comment]
To automatically install susieR when installing echolocator, you can list susieR in the Imports section. From the [vignette](https://github.com/r-lib/remotes/blob/7ffc74114904663f788e7331b4f20542df9fc16c/vignettes/dependencies.Rmd#L20):

> You can mark any regular dependency defined in the `Depends`, `Imports`,
`Suggests` or `Enhances` fields as being installed from a remote location by
adding the remote location to `Remotes` in your `DESCRIPTION` file. This will
cause remotes to download and install them from the specified location,
instead of CRAN.

Currently you list susieR in `Remotes` but not `Imports`:

https://github.com/RajLabMSSM/echolocatoR/blob/b055ac0fb74c914d7600e3afc650a2ffd7149396/DESCRIPTION#L18-L50

**Comment by bschilder** [comment]
Thanks for suggesting this fix, @jdblischak! Adding this now.
