### ISSUE TITLE
Issue when creating conda environment

### ISSUE THREAD

**Issue by keekov** [RajLabMSSM/echolocatoR#77]
After downloading echoR.yml file and running 
conda env create -f echoR.yml

the following is displayed:
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

after several hours, creating the environment eventually fails with a warning about package conflicts.  
There are many package conflicts and the output may be too lengthy to put here. 

commit 7bfdbce8c70d234ca6957d0608a454c2673305db works for me to build the environment but then I am unable to use MungeSumStats because this R package requires R >=4.1. This commit's .yml file specifies R 4.0. 

I have tried building the environment while running Linux Mint and using Miniconda3 version 4.11.0, using Windows 8 and Miniconda3 version 4.11.0, and on Linux CentOS-7 with Miniconda3 version  4.7.10 and 4.10.3. I have also tried Linux CentOS-7 with Miniconda2 version 4.7.10. All with the similar long output of conflicts.

[echolocatoR_conflicts.txt](https://github.com/RajLabMSSM/echolocatoR/files/8129662/echolocatoR_conflicts.txt)

**Comment by michaelofrancis** [comment]
I am having the exact same problem right now. Any help would be greatly appreciated!

**Comment by bschilder** [comment]
Hi @keekov and @michaelofrancis, thanks for reporting this.

I'm currently trying to find a way to get the echoR env to solve with r-mungesumstats, but this is a bit tricky because (as mentioned) it requires R>=4.1, which gives less options for all the other deps and thus makes it hard for conda to solve.

In the meantime, I'm going to revert echolocatoR's dev branch to the yaml found in [this commit here](https://github.com/RajLabMSSM/echolocatoR/raw/7bfdbce8c70d234ca6957d0608a454c2673305db/inst/conda/echoR.yml).

 While the env won't include `MungeSumstats`, you should still be able to use your main R library (outside of the conda env) to use this package, so long as your start the R session from outside the conda end (eg the usual desktop icon).

**Comment by bschilder** [comment]
Just updated the *inst/conda/echoR.yml* on master to use the old version that works.

**Comment by bschilder** [comment]
Just a note, in order to replace a version of the conda env that isn't working with one that is currently working (which is should be now), you'll need to first delete your old conda env:
```
conda env remove -n "echoR"
```

Then try rebuilding the echoR conda env via ` echoconda::yaml_to_env()` or via the command line directly.
